assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        []
    filters:
        cssrewrite: ~
        less:
            node: "%node.path%"
            node_paths: ["%node.modules%"]
            apply_to: "\\.less$"
        uglifyjs2:
            bin: "%uglify.js%"
        uglifycss:
            bin: "%uglify.css%"

    assets:
        # Bootstrap Assets
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js
            filters:
                - uglifyjs2
            output: js/bootstrap.min.js

        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less
            filters:
                - less
                - cssrewrite
                - uglifycss
            output: css/bootstrap.min.css

        # JQuery Assets
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.12.4.js
            filters:
                - uglifyjs2
            output: js/jquery.min.js
