imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }

    # Frontend Settings
    - { resource: settings/braincrafted_bootstrap.yml }

    # FOS Bundles
    - { resource: fos/fos_user.yml }

    # Knp Configurations
    - { resource: knp/knp_configs.yml }

    # Sonata Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_cache.yml }
    - { resource: sonata/sonata_intl.yml }
    - { resource: sonata/sonata_user.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ["twig"]
        #assets_version: SomeVer sionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    base_template_class: Sonata\CacheBundle\Twig\TwigTemplate14

    form:
        resources:
            - "SonataCoreBundle:Form:datepicker.html.twig"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default

        entity_managers:
            default:
                auto_mapping: true
                mappings: ~

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    encryption: "%mailer_encryption%"
    port:       "%mailer_port%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:     { type: memory }

# JMS Configuration
jms_di_extra:
    locations:
        all_bundles: false
        directories: ["%kernel.root_dir%/../src"]

    automatic_controller_injections:
        properties:
            request: "@request"
            router: "@router"
        method_calls:
            setRouter: ["@router"]

jms_security_extra:
    secure_all_services: false
    expressions: true
