imports:
    - { resource: config.yml }

framework:
    templating:
        engines: ["twig"]
        assets_version_format: "static-%%2$s/%%1$s"

    validation:
        enable_annotations: true

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
