imports:
    - { resource: config.yml }

doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver: apc
                query_cache_driver: apc
                result_cache_driver: apc

framework:
    templating:
        engines: ["twig"]
        assets_version_format: "static-%%2$s/%%1$s"

    validation:
        cache: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
