# Admin References.
#
# Cross links between kernels.
admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /{_locale}/admin
    requirements:
        _locale: "%locales%"
    defaults:
        _locale: "%locale%"

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/admin
    requirements:
        _locale: "%locales%"
    defaults:
        _locale: "%locale%"

sonata_user_admin_security:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"
    prefix: /{_locale}/admin
    requirements:
        _locale: "%locales%"
    defaults:
        _locale: "%locale%"

sonata_user_admin_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/admin_resetting.xml"
    prefix: /{_locale}/admin/resetting
    requirements:
        _locale: "%locales%"
    defaults:
        _locale: "%locale%"

_admin_login:
    path: /{_locale}/admin/login
    requirements:
        _locale: "%locales%"
    defaults:
        _locale: "%locale%"

_admin_login_check:
    path: /{_locale}/admin/login_check
    requirements:
        _locale: "%locales%"
    defaults:
        _locale: "%locale%"

_admin_logout:
    path: /{_locale}/admin/logout
    requirements:
        _locale: "%locales%"
    defaults:
        _locale: "%locale%"

sonata_user_admin_security_logout:
    path: /{_locale}/admin/logout
    requirements:
        _locale: "%locales%"
    defaults:
        _locale: "%locale%"

sonata_user_admin_security_check:
    path: /{_locale}/admin/login_check
    requirements:
        _locale: "%locales%"
    defaults:
        _locale: "%locale%"
