parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

security:
    encoders:
        Application\Sonata\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    acl:
        connection: default

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: "ROLE_ADMIN" }

    firewalls:
        # -> Disabling the security for the web debug toolbar, the profiler and assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> Custom firewall configuration for the admin area
        admin:
            switch_user:        true
            context:            user
            pattern:            ^/(.*)
            form_login:
                provider:       fos_userbundle
                login_path:     _admin_login
                use_forward:    false
                check_path:     _admin_login_check
                failure_path:   null
                use_referer:    true
            logout:
                path:           _admin_logout
                target:         _admin_login # May be replaced by the index path, e.g: website_default_index
            anonymous:          true

        # -> Defaut login area for standard users
        main:
            switch_user:        true
            context:            user
            pattern:            ^/(.*)
            form_login:
                provider:       fos_userbundle
                login_path:     _admin_login
                use_forward:    false
                check_path:     _admin_login_check
                failure_path:   null
            logout:             true
            anonymous:          true
            remember_me:
                secret:         "+hyho+oqry3^^n!g8(n@!(lf_%^^q34098wj_5l*7dqvvah4jp"
                lifetime:       172800
                path:           /
                domain:         ~

    access_control:
        # These admin login pages must be available to any user (anonymous role).
        - { path: ^/(%locales%)/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%locales%)/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%locales%)/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # All the routes after /(%locales%)/admin/ must be restricted and allowed to admins only.
        - { path: ^/(%locales%)/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
