knp_menu:
    twig:
        template: "BraincraftedBootstrapBundle:Menu:bootstrap.html.twig"

knp_paginator:
    template:
        pagination: "BraincraftedBootstrapBundle:Pagination:bootstrap.html.twig"
